# Generated by Django 5.2.6 on 2025-09-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_is_email_verified_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allow_platform_gateway',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(choices=[('pkr', 'PKR'), ('usd', 'USD')], default='pkr', max_length=3),
        ),
    ]
